import { StyleSheet } from "@react-pdf/renderer";

export default StyleSheet.create({
  document: {
    fontFamily: "Helvetica",
  },
  page: {
    display: "flex",
    justifyContent: "flex-start",
    flexDirection: "column",
    alignItems: "center",
    width: "100vw",
    backgroundColor: "white",
    paddingTop: 32,
    paddingBottom: 32,
  },
  section: {
    display: "flex",
    flexDirection: "row",
  },
  name: {
    alignSelf: "center",
    fontSize: 10,
    fontWeight: 700,
  },
  title: {
    display: "flex",
    justifyContent: "center",
    textAlign: "center",
    fontSize: 9,
    fontWeight: 400,
    marginBottom: 6,
    borderBottomWidth: 0.3,
  },
  contact: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    flexWrap: "wrap",
    alignSelf: "center",
    rowGap: 6,
    columnGap: 64,
    marginLeft: 16,
    marginRight: 16,
    paddingBottom: 4,
    width: "80%",
    borderBottomWidth: 0.3,
  },
  image: {
    width: 8,
    height: 8,
  },
  aboutMe: {
    marginTop: 2,
    marginBottom: 2,
    width: "80%",
    borderBottomWidth: 0.3,
    fontSize: 8,
    fontWeight: 400,
    lineHeight: 1.5,
  },
  sectionTitle: {
    fontSize: 8,
    fontWeight: 700,
    textAlign: "center",
    marginBottom: 4,
    marginTop: 4,
    alignSelf: "center",
    width: "80%",
    maxWidth: "128",
    borderBottom: 0.3,
    lineHeight: 1.5,
  },
  domainsSection: {
    display: "flex",
    flexDirection: "row",
    width: "80%",
    justifyContent: "flex-start",
    alignItems: "center",
    marginTop: 2,
    marginBottom: 2,
    paddingBottom: 4,
    borderBottomWidth: 0.3,
  },
  domainsSectionTitle: {
    fontSize: 8,
    fontWeight: 700,
    textAlign: "left",
    width: "25%",
  },
  domainsSectionText: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    fontSize: 8,
  },
  skillsSection: {
    marginTop: 2,
    marginBottom: 4,
    width: "80%",
    lineHeight: 0.8,
    fontSize: 8,
  },
  experienceSection: {
    paddingBottom: 2,
    marginBottom: 4,
    width: "80%",
    lineHeight: 0.6,
  },
  academicSection: {
    paddingBottom: 2,
    marginBottom: 4,
    width: "80%",
  },
  languagesSection: {
    paddingBottom: 2,
    marginBottom: 4,
    width: "80%",
  },
});
